# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  overrideGpg: true
  localBranchSortOrder: recency
keybinding:
  commits:
    moveDownCommit: "<c-d>" # move down
    moveUpCommit: "<c-u>" # move up
gui:
  nerdFontsVersion: "3"
  commitHashLength: 5
  filterMode: "fuzzy"
  theme:
    selectedLineBgColor:
      - "#42675A"
    cherryPickedCommitBgColor:
      - "#5DE4C7"
    cherryPickedCommitFgColor:
      - black
    optionsTextColor:
      - "#5DE4C7"
    inactiveBorderColor:
      - "#4F6477"
  spinner:
    frames:
      - "◐"
      - "◓"
      - "◑"
      - "◒"
    rate: 67
